/**
 * Generated by FITpro Fixture Generator
 */
package FIXTURES.client;

import GUI.LabGUI;
import fit.ActionFixture;
import models.Patient;
import client.*;
import enums.Status;
import models.Envelope;
import enums.task;
import models.LabSettings;

/*
 * TODO: modify class to match the FIT test - edit and add methods as required.
 */
public class LabRecord extends ActionFixture {

	public Patient pt;

	public boolean patient_exist;

	public boolean record_saved;

	public LabSettings labSet;

	public int labID;

	public String labSummery;

	public String labWorkerId;

	public LabController labController;



	public void labRecord(String lRecord) {

		this.labSummery = lRecord;
	}

	

	public void labRefNumber(int lRefNumber) {

		this.labID = lRefNumber;
	}

	public void labWorkerID(String lWorkerID) {
		this.labWorkerId = lWorkerID;
	}

	public boolean patientExist() {

		return patient_exist;
	}

	public void patientID(String ptID) {
		this.pt.setpID(ptID);
	}

	

	public boolean recordSaved() {

		return this.record_saved;
	}

	public void saveRecord() {

		labSet.setLabWorkerSummery(labSummery);
		labSet.setLabWorkerID(labWorkerId);
		Controller.Control(labSet, task.UPDATE_LAB_RECORD);
		this.record_saved = true;
	}

	public void searchPatient() {

		Envelope en = Controller.Control(this.pt, task.GET_PATIENT);
		if (en.getStatus() == Status.EXIST) {
			patient_exist = true;
		} else {
			patient_exist = false;
			this.record_saved = false;
		}
	}

	public void startLabRecord() {

		
		labSet = new LabSettings();
		labController = new LabController(new LabGUI(), this.labWorkerId);
		this.pt = new Patient();
	}

}
